
---
flowMonitorv9:
    rpc: get_config
    args:
        filter_xml: services/flow-monitoring/version9/template
        options:
            inherit: inherit
            groups: groups
    item: services/flow-monitoring/version9/template
    view: v9serviceView
v9serviceView:
    fields:
        v9_temp_name: name
        v9_ipv4_template: ipv4-template
        v9_ipv6_template: ipv6-template
        v9_mpls_template: mpls-template
        v9_act_timeout: flow-active-timeout
        v9_inact_timeout: flow-inactive-timeout
