---
flowMonitorIpFix:
    rpc: get_config
    args:
        filter_xml: services/flow-monitoring/version-ipfix/template
        options:
            inherit: inherit
            groups: groups

    item: services/flow-monitoring/version-ipfix/template
    view: serviceView
serviceView:
    fields:
        ipfix_temp_name: name
        ipfix_ipv4_template: ipv4-template
        ipfix_ipv6_template: ipv6-template
        ipfix_mpls_template: mpls-template
        ipfix_act_timeout: flow-active-timeout
        ipfix_inact_timeout: flow-inactive-timeout
