---
fpcConfig:
    rpc: get_config
    args:
        filter_xml: chassis/fpc
        options:
            inherit: inherit
            groups: groups
    item: chassis/fpc
    view: fpcView
fpcView:
    fields:
        fpc_number: name
        sample_inst_name: sampling-instance/name
        flow_tbl_size_ipv4: inline-services/flow-table-size/ipv4-flow-table-size
        flow_tbl_size_ipv6: inline-services/flow-table-size/ipv6-flow-table-size
        flow_tbl_size_mpls: inline-services/flow-table-size/mpls-flow-table-size
        extended_flow_mem: inline-services/use-extended-flow-memory
