---
fwdConfig:
    rpc: get_config
    args:
        filter_xml: forwarding-options/sampling/instance
        options:
            inherit: inherit
            groups: groups
    item: forwarding-options/sampling/instance
    view: sampleView
sampleView:
    fields:
        inst_name: name
        rate: input/rate
        family_inet: family/inet
        family_inet6: family/inet6
        family_mpls: family/mpls
        flow_server_v4: family/inet/output/flow-server/name
        flow_server_port_v4: family/inet/output/flow-server/port
        flow_server_v6: family/inet6/output/flow-server/name
        flow_server_port_v6: family/inet6/output/flow-server/port
        flow_server_mpls: family/mpls/output/flow-server/name
        flow_server_port_mpls: family/mpls/output/flow-server/port
        jflow_source_addr_v4: family/inet/output/inline-jflow/source-address
        jflow_source_addr_v6: family/inet6/output/inline-jflow/source-address
        jflow_source_addr_mpls: family/mpls/output/inline-jflow/source-address
