---
interfaceProxyArpConfigTable:
  get: interfaces/interface
  key: name
  view: interfaceProxyarpConfigView

interfaceProxyarpConfigView:
  fields:
    interface-name: name
    unit-name: unit/name
    restricted-config: {unit/proxy-arp/restricted: flag}
    proxy-arp-config: {unit/proxy-arp: flag}
    unrestricted-config: {unit/proxy-arp/unrestricted: flag}
