---
SystemTable:
  get: system
  key: Null
  view: SystemView

SystemView:
  fields:
    no-redirects: { no-redirects: flag }
    no-redirects-ipv6: { no-redirects-ipv6: flag }
    no-ping-record-route: { no-ping-record-route: flag }
    no-ping-time-stamp: { no-ping-time-stamp: flag }    
    source-quench: { internet-options/source-quench: flag }
    tcp-drop-synfin-set: { internet-options/tcp-drop-synfin-set: flag }
