---
SystemPortsTable:
  get: system
  key: Null
  view: SystemPortsView

SystemPortsView:
  fields:
    console-log-out-on-disconnect: { ports/console/log-out-on-disconnect: flag }
    console-insecure: { ports/console/insecure: flag }
    auxiliary-disable: { ports/auxiliary/disable: flag }
    auxiliary-insecure: { ports/auxiliary/insecure: flag }
    diag-port-authentication: { diag-port-authentication/encrypted-password: flag }
