---
snmpServerConfigTable:
  get: snmp/v3/target-address
  key: address
  view: snmpServerConfigView

snmpServerConfigView:
  fields:
    target-parameters: { target-parameters: flag }
    target-address-config: { ../target-address: flag }
    snmp-target-address: address
    snmp-target-name: name
    target-parameters-name: target-parameters