---
syslogConfigTable:
  get: system/syslog/host
  key: name
  view: syslogConfigView

syslogConfigView:
  fields:
    host-name: name
    enhanced-timestamp-year: { ../time-format/year: flag }
    enhanced-timestamp-millisec: { ../time-format/millisecond: flag }
    host-config: { ../host: flag }
